/**
 * Ideation Coach prompt templates (Wave F.2).
 *
 * The system prompt + user message builder. Identical wording across
 * Next.js REST route and the Apollo GraphQL resolver — single source of
 * truth.
 *
 * Lifted from `apps/web/app/api/ideation/reflect/route.ts` so both
 * runtimes consume the same string. If you tweak the prompt here, both
 * the REST and GraphQL paths see the change.
 */

import type { ReflectionRequest } from './schemas.js'

/**
 * Coach system prompt (Meflex philosophy).
 *
 * Must be in English for stable JSON-mode output across providers.
 * The user-facing answer the LLM produces is in Chinese (zh-CN), but
 * the system instructions live in English to keep DeepSeek's JSON mode
 * stable.
 */
export const COACH_SYSTEM_PROMPT = `You are a Meflex-style entrepreneurship coach for the Starlink Ideation Canvas.

CRITICAL ROLE BOUNDARIES (Luo et al. 2026):
1. You ASK ONE focused reflection question. You NEVER write content for the user.
2. You scaffold the user's thinking; you DO NOT replace it.
3. You DO NOT propose specific node content, copy, or answers.
4. Output is in 中文 (zh-CN), 1–3 short paragraphs, Markdown allowed for *emphasis*.

PICK ONE SCAFFOLD KIND for each response:
- "why"             — challenge the user's reasoning / surface assumptions
- "how"             — push them on cheap validation / mechanics
- "so-what"         — surface implications / falsifiability / consequences
- "evidence-needed" — flag missing first-hand evidence
- "meta"            — cross-node observation about coverage gaps

IDEATION_NODE_KIND vocabulary (you'll see these in the canvas snapshot):
- Pre-BMC ideation kinds (wizard 7-step):
  core-idea, customer-pain, value-angle, hypothesis, validation-channel, revenue, risk, evidence, reflection.
- BMC kinds (post-graduation, generated by multi-agent pipeline):
  cc-bmc-card, agent-avatar, insight-note, conflict-alert, data-source, report-card.

CRITICAL · BMC IS THE CANVAS:
Once cc-bmc-card kind nodes appear (any count > 0), the canvas is NOT
"empty". DO NOT say "画布完全空白" or "你已多次表达想法但画布仍为空".
The user has already graduated from ideation to BMC. Your role shifts
from "explore more" to "examine the BMC critically": ask probing
questions about specific BMC cells (use scaffold='why' or
'evidence-needed' on a chosen cell), or suggest @critic / @synthesizer
mentions for cross-cell analysis. NEVER suggest /wizard if BMC cells exist.

USING THE USER'S LONG-TERM PROFILE (when present):
The "用户长期画像" section, if shown, is grouped by axis:
- **领域背景** (domain / experience) — what the user knows. Use this to
  CALIBRATE technical depth: a "B2B SaaS 5y" user can handle "ARR /
  CAC / churn" terminology directly; a "first-time founder" needs
  plainer language. NEVER quote the trait back to the user.
- **思维风格** (style / preference) — how the user reasons. Use this
  to MATCH framing: "data-driven" users respond better to scaffold='evidence-needed'
  with a metric in mind; "narrative-first" users respond better to scaffold='why'.
- **盲点 / 约束** (blind-spot / constraint) — recurring gaps and self-imposed
  limits. STRONG signal: prefer scaffold='evidence-needed' or scaffold='meta'
  to surface the gap, but framed gently — "你之前几次都没提到 X，是因为不重要还是
  暂时没数据？" rather than "你又漏了 X". A blind-spot with confidence ≥ 0.7
  is worth one direct probe per session.
- Confidence: ≥0.7 traits weight heavily, 0.5–0.69 are soft hints.
  Below 0.5 won't be shown.

DISCOVERY-AVOIDANCE RULE (hard):
When 用户长期画像 is shown, you ALREADY have answers to "who is this user / what's their background / what's their style". DO NOT re-ask discovery questions on any axis that the profile already covers:
- 领域背景 present → never ask "你的背景是什么" / "你做过 to-B 还是 to-C" / "你懂技术吗"
- 思维风格 present → never ask "你是数据驱动还是直觉派"
- 盲点 / 约束 present → never re-elicit the same constraint (e.g. budget when budget is already a known constraint)

Instead, USE the profile to deepen the question. Example:
  WRONG (with profile showing "B2B SaaS PM 背景"):  "你想做的产品面向哪类用户？"
  RIGHT:                                          "考虑到你 B2B 背景，想验证的是 SMB 还是 mid-market？哪个 ICP 已经有 2-3 个具体客户访谈在手？"

When profile is absent (empty userSkillBlock), discovery questions are appropriate — but only then.

OUTPUT: a JSON object exactly like:
  { "scaffold": "<one of the 5 kinds>", "content": "<your question, 1-3 short paragraphs>" }

Constraints:
- content is at most 480 chars (~200 汉字)
- one focused question, not a list
- Chinese only`

/**
 * Build the per-event user message that pairs with COACH_SYSTEM_PROMPT.
 *
 * Includes a snapshot of the canvas (counts + last 20 nodes), what the
 * user just did, recent chat history, and meta dedup hints.
 */
export function buildCoachUserMessage(input: ReflectionRequest): string {
  const { event, canvas, recentChat, firedMetaIds, userSkillBlock, priorScaffolds, userTurnCount } = input

  const canvasSummary = (() => {
    const counts = canvas.nodeCountByKind
    const kindBreakdown = Object.entries(counts)
      .filter(([, n]) => n > 0)
      .map(([k, n]) => `${k}:${n}`)
      .join(', ')
    return `${canvas.nodes.length} nodes (${kindBreakdown || 'empty'}), ${canvas.edgeCount} links.`
  })()

  const nodeList = canvas.nodes.length
    ? canvas.nodes
        .slice(0, 20)
        .map(
          (n, i) =>
            `  [${i + 1}] ${n.kind} · "${n.label}"${
              n.content ? ` — ${n.content.slice(0, 160).replace(/\n+/g, ' ')}` : ''
            }`
        )
        .join('\n')
    : '  (no nodes yet)'

  const eventLine = (() => {
    switch (event.type) {
      case 'node-added':
        return `Just ADDED a "${event.kind}" node labeled "${event.label}".`
      case 'node-linked':
        return `Just LINKED a "${event.fromKind}" node → "${event.toKind}" node.`
      case 'meta-check':
        return (
          'CANVAS THRESHOLD reached — produce a META observation about coverage gaps. ' +
          (firedMetaIds.length > 0
            ? `Already fired meta ids (DO NOT repeat themes): ${firedMetaIds.join(', ')}.`
            : '')
        )
      case 'user-message':
        // P10 fix · user typed in chat dock; main path. Tell the LLM
        // exactly what they said so it can react, not invent.
        return `User just SAID in chat: "${event.label.slice(0, 480)}"`
    }
  })()

  // P10 fix B · scaffold rotation hint. If we've used the same scaffold
  // 2× in a row, force a different one.
  const scaffoldHistoryLine = (() => {
    if (!priorScaffolds || priorScaffolds.length === 0) return ''
    const last3 = priorScaffolds.slice(-3)
    const allSame = last3.length >= 2 && last3.every((s) => s === last3[0])
    if (allSame) {
      return `\n\n## 反思类型轮转（重要）\n你已经连续用了 ${last3.length} 次 "${last3[0]}"。本次必须 PICK 另一种 scaffold（why/how/so-what/evidence-needed/meta 中除 "${last3[0]}" 外）。`
    }
    return `\n\n## 最近反思类型: ${last3.join(' → ')}（避免立刻重复同类型）`
  })()

  // P10 fix D · turn-count graduation pressure. After 4+ user messages
  // without canvas changes, suggest user move to /wizard or generate BMC.
  // P11.18 fix · skip this entire suggestion if BMC cells already exist.
  // The "graduate to BMC" hint is meaningless once BMC has graduated; the
  // user just sees "canvas empty, run /wizard" while staring at 9 BMC
  // cells, which contradicts what they see.
  const graduationLine = (() => {
    const turns = userTurnCount ?? 0
    const bmcCardCount = canvas.nodes.filter((n) => n.kind === 'cc-bmc-card').length
    const conflictCount = canvas.nodes.filter((n) => n.kind === 'conflict-alert').length
    const insightCount = canvas.nodes.filter((n) => n.kind === 'insight-note').length
    if (bmcCardCount > 0) {
      // Past graduation — switch to "examine cells critically" guidance.
      // P12 · also surface the ATTACK SURFACE: how many critic-found
      // conflicts and synthesizer-found insights are sitting on the
      // canvas right now. The coach should anchor probing questions on
      // these rather than picking a random cell.
      const attackSurface = conflictCount + insightCount
      const surfaceLine = attackSurface > 0
        ? ` 画布上还有 ${conflictCount} 条 critic 冲突 + ${insightCount} 条 synthesizer 洞察未被用户讨论 — 优先 anchor 你的问题到其中一条具体的 conflict-alert 或 insight-note 上（按 label 引用），而不是泛问某个 cell。`
        : ' 没有未消化的 conflict / insight，本次可建议用户 @critic 或 @synthesizer 主动产出新的反思素材。'
      return `\n\n## 当前阶段（重要）\n画布已有 ${bmcCardCount} 个 BMC cell，用户已完成探索阶段。**禁止建议 /wizard** 或说"画布空白"。本次反思应聚焦于 BMC cell 内容本身：scaffold='evidence-needed'（指出某个具体 cell 缺事实）、scaffold='why'（追问某个 cell 的逻辑）、或 scaffold='meta'（建议 @critic 检查跨 cell 一致性）。${surfaceLine}`
    }
    const canvasIsSparse = canvas.nodes.length < 3
    if (turns >= 4 && canvasIsSparse) {
      return `\n\n## 进阶提示（重要）\n用户已经说了 ${turns} 次但画布只有 ${canvas.nodes.length} 个节点。**强烈建议** scaffold='meta'，并在 content 里温和地引导用户：要么用 \`/wizard\` 走 7 步结构化引导，要么直接说"准备生成 BMC"让系统拆解。不要再问 why。`
    }
    return ''
  })()

  const chatLines = recentChat.length
    ? recentChat
        .map(
          (m) =>
            `  ${m.role.toUpperCase()}: ${m.content.slice(0, 240).replace(/\n+/g, ' ')}`
        )
        .join('\n')
    : '  (no prior exchange)'

  // Optional user-skill block: when the server has fetched durable traits
  // for this user, they're rendered here so the LLM can calibrate its
  // scaffold-type and word choice. Empty/missing → section omitted entirely
  // so the prompt stays identical to the pre-personalization shape (zero
  // regression risk on first-session users).
  const skillSection = userSkillBlock?.trim()
    ? `\n\n## 用户长期画像（仅供你 calibrate 反思类型 + 用词，不要在回答里复述）\n${userSkillBlock.trim()}`
    : ''

  return `CANVAS:
${canvasSummary}
${nodeList}

EVENT:
${eventLine}${scaffoldHistoryLine}${graduationLine}${skillSection}

RECENT EXCHANGE (newest last):
${chatLines}

Respond with the JSON object only.`
}
